var output = `
  <body>
    <h1>Hello Web 414</h1>
    <p>This response was generated by a lambda function that was created by terraform!</p>
  </body>
`;
exports.handler = function(event, context, callback) {
  var out = {
    statusCode: '200',
    body: output,
    headers: {
      'Content-Type': 'text/html',
    },
  };
  callback(null, out);
};
